apiVersion: apps/v1
kind: Deployment
metadata:
  name: prytaneum-server
  labels:
    app: prytaneum-server
  namespace: dev
spec:
  selector:
    matchLabels:
      app: prytaneum-server
  replicas: 1
  template:
    metadata:
      labels:
        app: prytaneum-server
    spec:
      containers:
        - name: prytaneum-server
          image: gcr.io/PROJECT_ID/SERVER_IMAGE:TAG
          imagePullPolicy: IfNotPresent
          restartPolicy: Always
          env:
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  key: NODE_ENV
                  name: prytaneum-config-druj
            - name: HOST
              valueFrom:
                configMapKeyRef:
                  key: HOST
                  name: prytaneum-config-druj
            - name: SERVER_PORT
              valueFrom:
                configMapKeyRef:
                  key: SERVER_PORT
                  name: prytaneum-config-druj
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  key: username
                  name: prod-db-secret
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: prod-db-secret
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  key: database
                  name: prod-db-secret
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  key: host
                  name: prod-db-secret
