name: Merge Linting

on:
  pull_request_target:
    types: [closed]
  pull_request:
    types: [closed]

jobs:
  linting:
    name: Linting
    runs-on: ubuntu-latest
    environment: development
    if: ${{ github.event.pull_request.merged == true }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Yarn Install
        run: yarn install

      - name: Lint Client
        run: yarn workspace @app/client lint
